# Generated by Django 5.0.4 on 2024-05-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.TextField()),
                ('date', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
